#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

import vpngate_kr_mihomo_benchmark_v6 as base
import vpngate_kr_mihomo_optimized as optimized

SCRIPT_VERSION = "v7.3"

# Tuned for a low-latency Windows gaming workload rather than the generic
# "always switch to the absolute fastest probe" behavior of v7.2.
DEFAULT_TEST_URL = "http://www.gstatic.com/generate_204"
DEFAULT_EXPECTED_STATUS = "204"
DEFAULT_HEALTH_INTERVAL = 60
DEFAULT_HEALTH_TIMEOUT_MS = 3000
DEFAULT_MAX_FAILED_TIMES = 2
DEFAULT_TOLERANCE_MS = 5
DEFAULT_LAZY = False

optimized.SCRIPT_VERSION = SCRIPT_VERSION
optimized.DEFAULT_TEST_URL = DEFAULT_TEST_URL
optimized.DEFAULT_EXPECTED_STATUS = DEFAULT_EXPECTED_STATUS
optimized.DEFAULT_HEALTH_INTERVAL = DEFAULT_HEALTH_INTERVAL
optimized.DEFAULT_HEALTH_TIMEOUT_MS = DEFAULT_HEALTH_TIMEOUT_MS
optimized.DEFAULT_MAX_FAILED_TIMES = DEFAULT_MAX_FAILED_TIMES

_ORIGINAL_VALIDATE_CANDIDATE = optimized.validate_candidate
_ORIGINAL_PARSE_OVPN = base.parse_ovpn


def _validate_stable_openvpn_compat(candidate: base.Candidate) -> None:
    parsed = _ORIGINAL_PARSE_OVPN(candidate.ovpn)
    # Mihomo stable v1.19.30 has an OpenVPN tls-auth bug when the HMAC digest
    # differs from the historical SHA-1 behavior. Keep the generated stable
    # subscription on the known-good side of that boundary. The upstream bug
    # was fixed later on the development branch.
    if parsed["tls_auth"]:
        auth = (parsed["auth"] or "SHA1").strip().upper()
        if auth != "SHA1":
            raise ValueError(
                "OpenVPN tls-auth with non-SHA1 auth is excluded for Mihomo stable compatibility"
            )


def validate_candidate_v73(row: dict[str, str]) -> tuple[base.Candidate | None, str | None]:
    candidate, error = _ORIGINAL_VALIDATE_CANDIDATE(row)
    if candidate is None:
        return None, error
    try:
        _validate_stable_openvpn_compat(candidate)
    except Exception as exc:
        return None, str(exc)
    return candidate, None


optimized.validate_candidate = validate_candidate_v73


def build_config_strict_v73(
    candidates: list[base.Candidate],
    out_path: Path,
) -> tuple[int, list[base.Candidate]]:
    proxies: list[dict[str, Any]] = []
    names: list[str] = []
    emitted: list[base.Candidate] = []
    seen_endpoints: set[tuple[str, int]] = set()

    for candidate in candidates:
        try:
            _validate_stable_openvpn_compat(candidate)
            parsed = _ORIGINAL_PARSE_OVPN(candidate.ovpn)
            endpoint = (base._safe_server(parsed["server"]).lower(), parsed["port"])
            if endpoint in seen_endpoints:
                continue
            index = len(proxies) + 1
            clean = base.clean_name(candidate.hostname or candidate.ip.replace(".", "-"))
            name = f"KR-{index:02d}-{clean}"
            proxy = base.ovpn_to_mihomo(candidate.ovpn, name)
            proxies.append(proxy)
            names.append(name)
            emitted.append(candidate)
            seen_endpoints.add(endpoint)
        except Exception as exc:
            print(f"[skip-config] {candidate.hostname or candidate.ip}: {exc}")

    if not proxies:
        raise RuntimeError("no usable Mihomo proxies remain after final compatibility filtering")

    config = {
        "mode": "rule",
        "find-process-mode": "strict",
        "unified-delay": True,
        "profile": {
            "store-selected": True,
        },
        "proxies": proxies,
        "proxy-groups": [
            {
                "name": "KR-LOWEST",
                "type": "url-test",
                "proxies": names,
                "url": DEFAULT_TEST_URL,
                "interval": DEFAULT_HEALTH_INTERVAL,
                "timeout": DEFAULT_HEALTH_TIMEOUT_MS,
                # Do not churn between nearly identical routes during a game.
                "tolerance": DEFAULT_TOLERANCE_MS,
                # Keep the group warmed up so the first game packet does not
                # have to wait for a cold health-check cycle.
                "lazy": DEFAULT_LAZY,
                "max-failed-times": DEFAULT_MAX_FAILED_TIMES,
                "expected-status": int(DEFAULT_EXPECTED_STATUS),
                "disable-udp": False,
            }
        ],
        "rules": [
            "PROCESS-NAME,FreeStyleReboot.exe,KR-LOWEST",
            "MATCH,DIRECT",
        ],
        "tun": {
            "enable": True,
            "stack": "system",
            "auto-route": True,
            "auto-detect-interface": True,
        },
    }

    validate_config_v73(config)
    text = (
        f"# VPN Gate KR Mihomo subscription generated by benchmark {SCRIPT_VERSION}\n"
        + yaml.safe_dump(config, allow_unicode=True, sort_keys=False, width=120)
    )
    out_path.write_text(text, encoding="utf-8")

    loaded = yaml.safe_load(text)
    if not isinstance(loaded, dict):
        raise RuntimeError("YAML reload failed")
    validate_config_v73(loaded)
    return len(proxies), emitted


def write_metadata_v73(out: Path, candidates: list[base.Candidate]) -> None:
    selected: list[dict[str, Any]] = []
    for candidate in candidates:
        parsed = _ORIGINAL_PARSE_OVPN(candidate.ovpn)
        selected.append(
            {
                "hostname": candidate.hostname,
                "ip": candidate.ip,
                "profile_server": base._safe_server(parsed["server"]),
                "profile_port": parsed["port"],
                "ping": candidate.ping,
                "speed_bps": candidate.speed_bps,
                "score": candidate.score,
                "country_long": candidate.country_long,
                "country_short": candidate.country_short,
                "udp_port": parsed["port"],
            }
        )

    (out / "source_candidates.json").write_text(
        json.dumps(
            {
                "source_api": base.API_URL,
                "source_udp_endpoint_discovery": base.HTML_URL,
                "script_version": SCRIPT_VERSION,
                "base_parser_version": base.SCRIPT_VERSION,
                "ping_threshold_ms_exclusive": base.MAX_CSV_PING_MS,
                "health_check_url": DEFAULT_TEST_URL,
                "health_check_expected_status": int(DEFAULT_EXPECTED_STATUS),
                "health_check_interval_seconds": DEFAULT_HEALTH_INTERVAL,
                "health_check_timeout_ms": DEFAULT_HEALTH_TIMEOUT_MS,
                "health_check_tolerance_ms": DEFAULT_TOLERANCE_MS,
                "health_check_lazy": DEFAULT_LAZY,
                "health_check_max_failed_times": DEFAULT_MAX_FAILED_TIMES,
                "selected": selected,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def validate_config_v73(config: dict[str, Any]) -> None:
    proxies = config.get("proxies")
    groups = config.get("proxy-groups")
    rules = config.get("rules")
    tun = config.get("tun")

    if not isinstance(proxies, list) or not 1 <= len(proxies) <= base.MAX_PROXIES:
        raise RuntimeError("invalid generated proxy count")
    if not isinstance(groups, list) or len(groups) != 1:
        raise RuntimeError("expected exactly one proxy-group")
    if rules != [
        "PROCESS-NAME,FreeStyleReboot.exe,KR-LOWEST",
        "MATCH,DIRECT",
    ]:
        raise RuntimeError("unexpected routing rules")
    if not isinstance(tun, dict):
        raise RuntimeError("TUN configuration missing")
    if tun.get("enable") is not True or tun.get("stack") != "system":
        raise RuntimeError("unexpected TUN stack configuration")
    if tun.get("auto-route") is not True or tun.get("auto-detect-interface") is not True:
        raise RuntimeError("unexpected TUN routing configuration")

    names: list[str] = []
    for proxy in proxies:
        if not isinstance(proxy, dict) or proxy.get("type") != "openvpn":
            raise RuntimeError("non-OpenVPN proxy emitted")
        if proxy.get("proto") != "udp" or proxy.get("udp") is not True:
            raise RuntimeError(f"non-UDP proxy emitted: {proxy.get('name')}")
        name = proxy.get("name")
        if not isinstance(name, str) or not name:
            raise RuntimeError("proxy name missing")
        names.append(name)
        port = proxy.get("port")
        if not isinstance(port, int) or not 1 <= port <= 65535:
            raise RuntimeError(f"invalid OpenVPN port: {name}")

        has_userpass = "username" in proxy or "password" in proxy
        has_cert = "cert" in proxy
        has_key = "key" in proxy
        if has_cert != has_key or (has_userpass and (has_cert or has_key)):
            raise RuntimeError(f"invalid authentication mode: {name}")
        if not has_userpass and not has_cert:
            raise RuntimeError(f"authentication missing: {name}")

        if "tls-auth" in proxy and proxy.get("key-direction") not in {"0", "1"}:
            raise RuntimeError(f"invalid key-direction: {name}")
        if "tls-auth" in proxy and str(proxy.get("auth", "SHA1")).upper() != "SHA1":
            raise RuntimeError(f"tls-auth non-SHA1 profile must not be emitted: {name}")
        if "tls-auth" in proxy and ("tls-crypt" in proxy or "tls-crypt-v2" in proxy):
            raise RuntimeError(f"mutually-exclusive TLS settings: {name}")
        if "tls-crypt" in proxy and "tls-crypt-v2" in proxy:
            raise RuntimeError(f"mutually-exclusive TLS crypt settings: {name}")

        for field in base.PEM_FIELDS:
            value = proxy.get(field)
            if isinstance(value, str) and "BEGIN " in value and "\n" not in value:
                raise RuntimeError(f"PEM newline corruption: {name}:{field}")

    group = groups[0]
    if not isinstance(group, dict) or group.get("name") != "KR-LOWEST" or group.get("type") != "url-test":
        raise RuntimeError("KR-LOWEST url-test group missing")
    if group.get("proxies") != names:
        raise RuntimeError("KR-LOWEST proxy list mismatch")
    if group.get("url") != DEFAULT_TEST_URL:
        raise RuntimeError("unexpected health-check URL")
    if group.get("expected-status") != int(DEFAULT_EXPECTED_STATUS):
        raise RuntimeError("unexpected expected-status")
    if group.get("interval") != DEFAULT_HEALTH_INTERVAL:
        raise RuntimeError("unexpected health-check interval")
    if group.get("timeout") != DEFAULT_HEALTH_TIMEOUT_MS:
        raise RuntimeError("unexpected health-check timeout")
    if group.get("tolerance") != DEFAULT_TOLERANCE_MS:
        raise RuntimeError("unexpected health-check tolerance")
    if group.get("lazy") is not DEFAULT_LAZY:
        raise RuntimeError("unexpected lazy setting")
    if group.get("max-failed-times") != DEFAULT_MAX_FAILED_TIMES:
        raise RuntimeError("unexpected max-failed-times")
    if group.get("disable-udp") is not False:
        raise RuntimeError("UDP must remain enabled")

    profile = config.get("profile")
    if not isinstance(profile, dict) or profile.get("store-selected") is not True:
        raise RuntimeError("profile.store-selected must be enabled")


optimized.build_config_strict = build_config_strict_v73
optimized.write_metadata = write_metadata_v73


if __name__ == "__main__":
    raise SystemExit(optimized.main())
