#!/usr/bin/env python3
"""Optimized VPN Gate KR -> Mihomo generator.

The existing v7.1 parser/validator remains the compatibility source of truth.
This runner improves execution without changing the generated Clash Verge/Mihomo
policy: UDP-only OpenVPN, the same candidate ordering, and the same TUN/url-test
settings are preserved.
"""
from __future__ import annotations

import argparse
import json
import re
import statistics
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

import requests
import yaml

import vpngate_kr_mihomo_benchmark_v6 as base

SCRIPT_VERSION = "v7.2"
DEFAULT_WORKERS = 4
DEFAULT_BATCH_SIZE = 8


def new_session() -> requests.Session:
    session = requests.Session()
    session.headers.update({"User-Agent": base.USER_AGENT})
    return session


def validate_candidate(
    row: dict[str, str],
    udp_endpoints: dict[str, list[base.UDPEndpoint]],
) -> tuple[base.Candidate | None, str | None]:
    """Validate one CSV row in an isolated HTTP session.

    requests.Session is intentionally not shared across worker threads.
    """
    session = new_session()
    try:
        return base.candidate_from_row(row, session, udp_endpoints), None
    except Exception as exc:  # candidate rejection must not abort the batch
        return None, str(exc)
    finally:
        session.close()


def build_config_strict(candidates: list[base.Candidate], out_path: Path) -> tuple[int, list[base.Candidate]]:
    """Build config while making emitted-candidate accounting exact.

    v7.1 records source metadata before build-time conversion. If a later
    conversion were to fail, metadata and proxy count could diverge. We instead
    preflight every candidate with the exact same converter and only emit the
    candidates that can actually become Mihomo proxies.
    """
    proxies: list[dict[str, Any]] = []
    names: list[str] = []
    emitted: list[base.Candidate] = []
    seen_endpoints: set[tuple[str, int]] = set()

    for candidate in candidates:
        endpoint = (
            base._safe_server(base.parse_ovpn(candidate.ovpn)["server"]).lower(),
            candidate.udp_port,
        )
        if endpoint in seen_endpoints:
            continue

        index = len(proxies) + 1
        clean = base.clean_name(candidate.hostname or candidate.ip.replace(".", "-"))
        name = f"KR-{index:02d}-{clean}"
        try:
            proxy = base.ovpn_to_mihomo(candidate.ovpn, name)
        except Exception as exc:
            print(f"[skip-config] {candidate.hostname or candidate.ip}: {exc}")
            continue

        seen_endpoints.add(endpoint)
        proxies.append(proxy)
        names.append(name)
        emitted.append(candidate)

    config = {
        "mode": "rule",
        "unified-delay": True,
        "proxies": proxies,
        "proxy-groups": [
            {
                "name": "KR-LOWEST",
                "type": "url-test",
                "proxies": names,
                "url": base.DEFAULT_TEST_URL,
                "interval": 60,
                "timeout": 3000,
                "tolerance": 0,
                "lazy": True,
                "expected-status": 200,
                "disable-udp": False,
            }
        ],
        "rules": ["PROCESS-NAME,FreeStyleReboot.exe,KR-LOWEST", "MATCH,DIRECT"],
        "tun": {
            "enable": True,
            "stack": "system",
            "auto-route": True,
            "auto-detect-interface": True,
        },
    }
    base.validate_config(config, min_proxies=1)
    text = (
        f"# VPN Gate KR Mihomo subscription generated by benchmark {SCRIPT_VERSION}\n"
        + yaml.safe_dump(config, allow_unicode=True, sort_keys=False, width=120)
    )
    out_path.write_text(text, encoding="utf-8")
    loaded = yaml.safe_load(text)
    if not isinstance(loaded, dict):
        raise RuntimeError("YAML reload failed")
    base.validate_config(loaded, min_proxies=1)
    return len(proxies), emitted


def collect_candidates(
    eligible_rows: list[dict[str, str]],
    udp_endpoints: dict[str, list[base.UDPEndpoint]],
    limit: int,
    workers: int,
    batch_size: int,
) -> tuple[list[base.Candidate], int]:
    candidates: list[base.Candidate] = []
    seen_endpoints: set[tuple[str, int]] = set()
    invalid_profiles = 0
    cursor = 0

    with ThreadPoolExecutor(max_workers=workers, thread_name_prefix="vpngate") as pool:
        while cursor < len(eligible_rows) and len(candidates) < limit:
            batch = eligible_rows[cursor : cursor + batch_size]
            cursor += len(batch)
            futures = {
                pool.submit(validate_candidate, row, udp_endpoints): row
                for row in batch
            }
            batch_candidates: list[base.Candidate] = []
            for future in as_completed(futures):
                row = futures[future]
                candidate, error = future.result()
                if candidate is None:
                    invalid_profiles += 1
                    print(f"[skip] {row.get('HostName') or row.get('IP') or 'unknown'}: {error}")
                    continue
                endpoint = (
                    base._safe_server(base.parse_ovpn(candidate.ovpn)["server"]).lower(),
                    candidate.udp_port,
                )
                if endpoint in seen_endpoints:
                    print(f"[skip] {candidate.hostname or candidate.ip}: duplicate UDP endpoint")
                    continue
                seen_endpoints.add(endpoint)
                batch_candidates.append(candidate)

            candidates.extend(batch_candidates)

    candidates.sort(key=base._candidate_sort_key)
    return candidates[:limit], invalid_profiles


def write_metadata(out: Path, candidates: list[base.Candidate]) -> None:
    path = out / "source_candidates.json"
    path.write_text(
        json.dumps(
            {
                "source_api": base.API_URL,
                "source_udp_endpoint_discovery": base.HTML_URL,
                "script_version": SCRIPT_VERSION,
                "base_parser_version": base.SCRIPT_VERSION,
                "ping_threshold_ms_exclusive": base.MAX_CSV_PING_MS,
                "selected": [
                    {
                        "hostname": c.hostname,
                        "ip": c.ip,
                        "ping": c.ping,
                        "speed_bps": c.speed_bps,
                        "score": c.score,
                        "country_long": c.country_long,
                        "country_short": c.country_short,
                        "udp_port": c.udp_port,
                    }
                    for c in candidates
                ],
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def benchmark(
    names: list[str],
    session: requests.Session,
    controller: str,
    url: str,
    repeat: int,
    timeout_ms: int,
    secret: str | None,
    pause: float,
    expected_status: str | None,
) -> list[dict[str, Any]]:
    return base.benchmark(
        names,
        session,
        controller,
        url,
        repeat,
        timeout_ms,
        secret,
        pause,
        expected_status,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=base.MAX_PROXIES)
    parser.add_argument("--min-speed", type=int, default=base.DEFAULT_MIN_SPEED)
    parser.add_argument("--out-dir", default="vpngate_kr_benchmark")
    parser.add_argument("--controller", default="")
    parser.add_argument("--secret", default="")
    parser.add_argument("--url", default=base.DEFAULT_TEST_URL)
    parser.add_argument("--expected-status", default=base.DEFAULT_EXPECTED_STATUS)
    parser.add_argument("--repeat", type=int, default=5)
    parser.add_argument("--timeout", type=int, default=5000)
    parser.add_argument("--pause", type=float, default=0.3)
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS)
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)
    args = parser.parse_args()

    if not 1 <= args.limit <= base.MAX_PROXIES:
        raise SystemExit(f"--limit must be between 1 and {base.MAX_PROXIES}")
    if args.min_speed < 0:
        raise SystemExit("--min-speed must be >= 0")
    if not 1 <= args.workers <= 16:
        raise SystemExit("--workers must be between 1 and 16")
    if not 1 <= args.batch_size <= 32:
        raise SystemExit("--batch-size must be between 1 and 32")

    session = new_session()
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    print("[1/4] Downloading VPN Gate official CSV API...")
    csv_response = base._request(
        session,
        base.API_URL,
        accept="text/csv,text/plain;q=0.9,*/*;q=0.8",
    )
    rows = base.parse_official_csv(csv_response.text)
    print(f"        API rows: {len(rows)}")

    print("[2/4] Discovering official UDP OpenVPN endpoints...")
    html_response = base._request(
        session,
        base.HTML_URL,
        accept="text/html,application/xhtml+xml;q=0.9,*/*;q=0.8",
    )
    udp_endpoints = base.parse_official_udp_endpoints(html_response.text)
    print(f"        Korea IPs with UDP OpenVPN endpoint(s): {len(udp_endpoints)}")

    kr_rows = [
        row
        for row in rows
        if row.get("CountryShort", "").strip().upper() == "KR"
        and row.get("CountryLong", "").strip().lower() == "korea republic of"
    ]
    print(f"        Korea Republic of CSV rows: {len(kr_rows)}")

    eligible_rows: list[dict[str, str]] = []
    for row in kr_rows:
        ping = base._int_field(row.get("Ping"), default=None)
        speed = base._int_field(row.get("Speed"), default=None)
        if ping is None or not 0 <= ping < base.MAX_CSV_PING_MS:
            continue
        if args.min_speed and (speed is None or speed < args.min_speed):
            continue
        # Do not require CSV OpenVPN_ConfigData_Base64 here. The official server
        # table is already our fallback source for a real UDP profile.
        eligible_rows.append(row)

    eligible_rows.sort(
        key=lambda row: (
            base._int_field(row.get("Ping"), default=10**9),
            -(base._int_field(row.get("Speed"), default=0) or 0),
            -(base._int_field(row.get("Score"), default=0) or 0),
            row.get("HostName", "").lower(),
            row.get("IP", ""),
        )
    )
    print(f"        KR + Ping < {base.MAX_CSV_PING_MS} ms + speed filter: {len(eligible_rows)}")
    print(f"        parallel UDP validation: workers={args.workers}, batch={args.batch_size}")

    candidates, invalid_profiles = collect_candidates(
        eligible_rows,
        udp_endpoints,
        args.limit,
        args.workers,
        args.batch_size,
    )
    if len(candidates) < min(args.limit, base.MIN_PROXIES):
        raise RuntimeError(
            f"only {len(candidates)} valid UDP OpenVPN candidates remain; "
            f"required at least {min(args.limit, base.MIN_PROXIES)}"
        )

    print(f"        valid UDP OpenVPN profiles: {len(candidates)}")
    print(f"        rejected/invalid profiles: {invalid_profiles}")
    print(f"        selected: {len(candidates)}")

    yaml_path = out / "vpngate_kr_mihomo.yaml"
    count, emitted = build_config_strict(candidates, yaml_path)
    if count < min(args.limit, base.MIN_PROXIES):
        raise RuntimeError(
            f"only {count} Mihomo proxies were emitted after final conversion; "
            f"required at least {min(args.limit, base.MIN_PROXIES)}"
        )

    # Metadata is written only after final conversion, so it can never silently
    # claim nodes that were rejected during YAML generation.
    write_metadata(out, emitted)
    print(f"        generated: {yaml_path}")
    print(f"        YAML proxies: {count}")

    if args.controller:
        print("[4/4] Benchmarking through Mihomo /delay...")
        cfg = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        names = [proxy["name"] for proxy in cfg["proxies"]]
        results = benchmark(
            names,
            session,
            args.controller,
            args.url,
            args.repeat,
            args.timeout,
            args.secret or None,
            args.pause,
            args.expected_status or None,
        )
        (out / "benchmark_results.json").write_text(
            json.dumps(results, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        for index, result in enumerate(results, 1):
            print(
                f"{index:>2}. {result['name']:<42} "
                f"avg={result['avg_ms']} min={result['min_ms']} max={result['max_ms']} "
                f"jitter={result['jitter_ms']} timeout={result['timeouts']}"
            )
    else:
        print("[4/4] Live benchmark not requested.")

    session.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
