#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

import yaml

MIN_PROXIES = 3
MAX_PROXIES = 10
EXPECTED_VERSION = "v7.3"
EXPECTED_URL = "http://www.gstatic.com/generate_204"
EXPECTED_STATUS = 204
EXPECTED_INTERVAL = 60
EXPECTED_TIMEOUT = 3000
EXPECTED_TOLERANCE = 0
EXPECTED_LAZY = False
EXPECTED_MAX_FAILED_TIMES = 2


def fail(message: str) -> None:
    raise SystemExit(message)


def main() -> int:
    path = Path("build/vpngate_kr_mihomo.yaml")
    metadata_path = Path("build/source_candidates.json")
    if not path.is_file():
        fail("generated YAML does not exist")
    if not metadata_path.is_file():
        fail("candidate metadata does not exist")

    text = path.read_text(encoding="utf-8")
    if not text.startswith(f"# VPN Gate KR Mihomo subscription generated by benchmark {EXPECTED_VERSION}\n"):
        fail("unexpected generator version")
    cfg = yaml.safe_load(text)
    if not isinstance(cfg, dict):
        fail("generated YAML root is not a mapping")

    if cfg.get("find-process-mode") != "strict":
        fail("find-process-mode must be strict")
    if cfg.get("profile", {}).get("store-selected") is not True:
        fail("profile.store-selected must be enabled")

    proxies = cfg.get("proxies")
    groups = cfg.get("proxy-groups")
    rules = cfg.get("rules")
    tun = cfg.get("tun")
    if not isinstance(proxies, list) or not MIN_PROXIES <= len(proxies) <= MAX_PROXIES:
        fail("invalid generated proxy count")
    if not isinstance(groups, list) or len(groups) != 1:
        fail("expected exactly one proxy group")
    if rules != ["PROCESS-NAME,FreeStyleReboot.exe,KR-LOWEST", "MATCH,DIRECT"]:
        fail("unexpected routing rules")
    if not isinstance(tun, dict) or tun.get("enable") is not True:
        fail("TUN configuration missing/disabled")
    if tun.get("stack") != "system" or tun.get("auto-route") is not True or tun.get("auto-detect-interface") is not True:
        fail("unexpected TUN routing settings")

    allowed_ciphers = {"AES-128-GCM", "AES-256-GCM", "AES-128-CBC", "AES-256-CBC", "CHACHA20-POLY1305", "AES-CBC"}
    allowed_auth = {"MD5", "SHA1", "SHA256", "SHA384", "SHA512"}
    allowed_comp = {"yes", "no", "adaptive"}
    names: list[str] = []

    for proxy in proxies:
        if not isinstance(proxy, dict) or proxy.get("type") != "openvpn":
            fail("unexpected proxy type")
        if proxy.get("proto") != "udp" or proxy.get("udp") is not True:
            fail(f"non-UDP proxy emitted: {proxy.get('name')}")
        name = proxy.get("name")
        if not isinstance(name, str) or not name:
            fail("proxy name missing")
        names.append(name)
        server = proxy.get("server")
        port = proxy.get("port")
        if not isinstance(server, str) or not server:
            fail(f"OpenVPN server missing: {name}")
        if not isinstance(port, int) or not 1 <= port <= 65535:
            fail(f"invalid OpenVPN port: {name}")
        if not (("username" in proxy and "password" in proxy) or ("cert" in proxy and "key" in proxy)):
            fail(f"invalid OpenVPN authentication mode: {name}")
        if ("username" in proxy or "password" in proxy) and ("cert" in proxy or "key" in proxy):
            fail(f"mixed OpenVPN authentication modes: {name}")
        if "tls-auth" in proxy and proxy.get("key-direction") not in {"0", "1"}:
            fail(f"invalid key-direction: {name}")
        if "tls-auth" in proxy and str(proxy.get("auth", "SHA1")).upper() != "SHA1":
            fail(f"tls-auth non-SHA1 profile emitted: {name}")
        if "tls-auth" in proxy and ("tls-crypt" in proxy or "tls-crypt-v2" in proxy):
            fail(f"mutually-exclusive TLS settings: {name}")
        if "tls-crypt" in proxy and "tls-crypt-v2" in proxy:
            fail(f"mutually-exclusive TLS crypt settings: {name}")
        if proxy.get("cipher") is not None and str(proxy["cipher"]).upper() not in allowed_ciphers:
            fail(f"unsupported cipher: {name}")
        if proxy.get("auth") is not None and str(proxy["auth"]).upper() not in allowed_auth:
            fail(f"unsupported auth: {name}")
        if proxy.get("comp-lzo") is not None and str(proxy["comp-lzo"]).lower() not in allowed_comp:
            fail(f"unsupported comp-lzo: {name}")
        data_ciphers = proxy.get("data-ciphers")
        if data_ciphers is not None and (not isinstance(data_ciphers, list) or not data_ciphers):
            fail(f"invalid data-ciphers: {name}")
        if isinstance(data_ciphers, list) and any(str(x).upper() not in allowed_ciphers for x in data_ciphers):
            fail(f"unsupported data-ciphers: {name}")
        fallback = proxy.get("data-ciphers-fallback")
        if fallback is not None and str(fallback).upper() not in allowed_ciphers:
            fail(f"unsupported data-ciphers-fallback: {name}")
        for field in ("ca", "cert", "key", "tls-auth", "tls-crypt", "tls-crypt-v2"):
            value = proxy.get(field)
            if isinstance(value, str) and "BEGIN " in value and "\n" not in value:
                fail(f"PEM newline corruption: {name}:{field}")

    if len(names) != len(set(names)):
        fail("duplicate proxy names")

    group = groups[0]
    if group.get("name") != "KR-LOWEST" or group.get("type") != "url-test":
        fail("KR-LOWEST url-test group missing")
    if group.get("proxies") != names:
        fail("KR-LOWEST proxy list mismatch")
    if group.get("url") != EXPECTED_URL:
        fail("unexpected health-check URL")
    if group.get("expected-status") != EXPECTED_STATUS:
        fail("unexpected expected-status")
    if group.get("interval") != EXPECTED_INTERVAL or group.get("timeout") != EXPECTED_TIMEOUT:
        fail("unexpected health-check timing")
    if group.get("tolerance") != EXPECTED_TOLERANCE:
        fail("unexpected health-check tolerance")
    if group.get("lazy") is not EXPECTED_LAZY:
        fail("unexpected lazy setting")
    if group.get("max-failed-times") != EXPECTED_MAX_FAILED_TIMES:
        fail("unexpected max-failed-times")
    if group.get("disable-udp") is not False:
        fail("UDP must remain enabled")

    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    if metadata.get("source_api") != "https://www.vpngate.net/api/iphone/":
        fail("unexpected CSV API source")
    if metadata.get("source_udp_endpoint_discovery") != "https://www.vpngate.net/en/":
        fail("unexpected UDP endpoint discovery source")
    if metadata.get("script_version") != EXPECTED_VERSION or metadata.get("base_parser_version") != "v7.1":
        fail("unexpected generator/parser version")
    if metadata.get("ping_threshold_ms_exclusive") != 40:
        fail("unexpected Ping threshold")
    if metadata.get("health_check_url") != EXPECTED_URL or metadata.get("health_check_expected_status") != EXPECTED_STATUS:
        fail("unexpected health-check metadata")
    if metadata.get("health_check_interval_seconds") != EXPECTED_INTERVAL or metadata.get("health_check_timeout_ms") != EXPECTED_TIMEOUT:
        fail("unexpected health-check timing metadata")
    if metadata.get("health_check_tolerance_ms") != EXPECTED_TOLERANCE or metadata.get("health_check_lazy") is not EXPECTED_LAZY:
        fail("unexpected health-check policy metadata")
    if metadata.get("health_check_max_failed_times") != EXPECTED_MAX_FAILED_TIMES:
        fail("unexpected failure policy metadata")

    selected = metadata.get("selected")
    if not isinstance(selected, list) or len(selected) != len(proxies):
        fail("candidate metadata count does not match proxies")
    for index, item in enumerate(selected):
        if not isinstance(item, dict):
            fail(f"candidate metadata item {index + 1} is not an object")
        if item.get("country_short") != "KR" or item.get("country_long", "").lower() != "korea republic of":
            fail(f"candidate metadata item {index + 1} is not KR")
        if not isinstance(item.get("ping"), int) or not 0 <= item["ping"] < 40:
            fail(f"candidate metadata item {index + 1} has invalid Ping")
        if item.get("profile_server", item.get("ip")) != proxies[index].get("server"):
            fail(f"proxy {index + 1} server does not match metadata")
        if item.get("profile_port", item.get("udp_port")) != proxies[index].get("port"):
            fail(f"proxy {index + 1} port does not match metadata")
        if item.get("stable_proxy_name") != proxies[index].get("name"):
            fail(f"proxy {index + 1} stable name does not match metadata")

    print(f"validated proxies={len(proxies)}; endpoint fallback enabled; timeout={EXPECTED_TIMEOUT}ms; tolerance={EXPECTED_TOLERANCE}ms")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
